/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslationRouteImport } from './routes/translation'
import { Route as RotationRouteImport } from './routes/rotation'
import { Route as ReflectionRouteImport } from './routes/reflection'

const TranslationRoute = TranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => rootRouteImport,
} as any)
const RotationRoute = RotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionRoute = ReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reflection': typeof ReflectionRoute
  '/rotation': typeof RotationRoute
  '/translation': typeof TranslationRoute
}
export interface FileRoutesByTo {
  '/reflection': typeof ReflectionRoute
  '/rotation': typeof RotationRoute
  '/translation': typeof TranslationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/reflection': typeof ReflectionRoute
  '/rotation': typeof RotationRoute
  '/translation': typeof TranslationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/reflection' | '/rotation' | '/translation'
  fileRoutesByTo: FileRoutesByTo
  to: '/reflection' | '/rotation' | '/translation'
  id: '__root__' | '/reflection' | '/rotation' | '/translation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ReflectionRoute: typeof ReflectionRoute
  RotationRoute: typeof RotationRoute
  TranslationRoute: typeof TranslationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translation': {
      id: '/translation'
      path: '/translation'
      fullPath: '/translation'
      preLoaderRoute: typeof TranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotation': {
      id: '/rotation'
      path: '/rotation'
      fullPath: '/rotation'
      preLoaderRoute: typeof RotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflection': {
      id: '/reflection'
      path: '/reflection'
      fullPath: '/reflection'
      preLoaderRoute: typeof ReflectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ReflectionRoute: ReflectionRoute,
  RotationRoute: RotationRoute,
  TranslationRoute: TranslationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
